# This is used by standardrb

require:
  - standard
  - ./.rubocop/forbidden_methods.rb
  - ./.rubocop/test_base_class.rb

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120

Custom/ForbiddenMethods:
  Enabled: true

Custom/TestBaseClass:
  Enabled: true
