# For available configuration options, see:
#   https://github.com/standardrb/standard
ruby_version: 2.7

ignore:
  - 'smoketest/**/*'

require:
  - ./.rubocop/forbidden_methods.rb

Layout/LineLength:
  Max: 120

Custom/ForbiddenMethods:
  Enabled: true
