source "https://rubygems.org"

ruby "3.4.7"

gem "csv"
gem "puma", "~> 7.0"
gem "rails", "~> 8.0"
gem "redis"
gem "sidekiq", "~> 8.0"
gem "speedshop-cloudwatch", path: ".."
gem "webmock"

group :development, :test do
  gem "debug"
end
