name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / Puma ${{ matrix.puma }} / Sidekiq ${{ matrix.sidekiq }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'
        puma:
          - '6'
          - '7'
        sidekiq:
          - '7'
          - '8'
        exclude:
          - ruby: '2.7'
            puma: '7'
          - ruby: '2.7'
            sidekiq: '8'
          - ruby: '3.0'
            sidekiq: '8'
          - ruby: '3.1'
            sidekiq: '8'

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
        env:
          BUNDLE_GEMFILE: gemfiles/puma_${{ matrix.puma }}_sidekiq_${{ matrix.sidekiq }}.gemfile
      - name: Run the default task
        run: bundle exec rake
        env:
          BUNDLE_GEMFILE: gemfiles/puma_${{ matrix.puma }}_sidekiq_${{ matrix.sidekiq }}.gemfile
